#ifndef _AS3935_Library_Defs_h
#define _AS3935_Library_Defs_h

#define AS3935_OUT_OF_RANGE 255
#define AS3935_DIRECT_COMMAND 0x96

enum AS3935_REGISTERS {
  REGISTER_AFE_GAIN = 0x00,
  REGISTER_NF_LEV = 0x01,
  REGISTER_WDTH = 0x01,
  REGISTER_MIN_NUM_LIGH = 0x02,
  REGISTER_SREJ = 0x02,
  REGISTER_CL_STAT = 0x02,
  REGISTER_INT = 0x03,
  REGISTER_MASK_DIST = 0x03,
  REGISTER_LCO_FDIV = 0x03,
  REGISTER_DISTANCE = 0x03,
  REGISTER_OSCILATORS = 0x08,
  REGISTER_PRESET_DEFAULT = 0x3C,
  REGISTER_CALIB_RCO = 0x3D
};

enum AS3935_REGISTER_MASKS {
  MASK_PRESET_DEFAULT,
  MASK_CALIB_RCO = 0x0,
  MASK_INT = 0xF0,
  MASK_SREJ = 0xF0,
  MASK_WDTH = 0xF0,
  MASK_NF_LEV = 0x8F,
  MASK_AFE_GAIN = 0xC1,
  MASK_DISTANCE = 0x3F,
  MASK_LCO_FDIV = 0x3F,
  MASK_MIN_NUM_LIGH = 0xCF,
  MASK_MASK_DIST = 0xDF,
  MASK_CL_STAT = 0xBF,
  MASK_OSCILATORS = 0xE0
};

enum AS3935_REGISTER_PARAMS_POSITION {
  POSITION_DISTANCE = 0,
  POSITION_INT = 0,
  POSITION_SREJ = 0,
  POSITION_WDTH = 0,
  POSITION_PRESET_DEFAULT = 0,
  POSITION_CALIB_RCO = 0,
  POSITION_OSCILATORS = 0,
  POSITION_AFE_GAIN = 1,
  POSITION_MIN_NUM_LIGH = 4,
  POSITION_NF_LEV = 4,
  POSITION_MASK_DIST = 5,
  POSITION_CL_STAT = 6,
  POSITION_LCO_FDIV = 6
};

enum AS3935_AFE_GAIN { AFE_GAIN_INDOOR = 0x12, AFE_GAIN_OUTDOOR = 0xE };

enum AS3936_INT { INT_NOISE = 0x01, INT_DISTURBER = 0x04, INT_STRIKE = 0x08 };

#endif
